version: '3.8'

services:
  backend:
    build: ./backend
    container_name: online-test-backend
    ports:
      - "8080:5000"
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - mern-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: online-test-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
